// Import the Emscripten generated module
// Note: This file will be generated by the build process and placed in the public directory
import GNGModule from '/gng_web.js';

const canvas = document.getElementById('canvas');
const statusElement = document.getElementById('status');

// Helper to update status
function setStatus(text) {
  if (!statusElement) return;

  // Clean up emscripten status messages
  const match = text.match(/([^(]+)\((\d+(\.\d+)?)\/(\d+)\)/);
  if (match) {
    const now = Date.now();
    if (now - setStatus.lastTime < 30) return; // Throttling
    setStatus.lastTime = now;
    text = `Downloading... ${match[2]}/${match[4]}`;
  }

  statusElement.innerText = text;

  if (text === 'Running...') {
      // Hide status after a moment when running
      setTimeout(() => {
          if(statusElement) statusElement.style.display = 'none';
      }, 1000);
  } else {
      statusElement.style.display = 'block';
  }
}
setStatus.lastTime = 0;

const config = {
  canvas: canvas,
  arguments: [
    'gng',              // Driver name
    '-rompath', '/roms', // Virtual ROM path (mapped via --embed-file)
    '-window',          // Window mode
    '-verbose',         // Verbose output
    '-skip_gameinfo',   // Skip info screen
    '-samplerate', '48000',
    '-audio_latency', '1'
  ],
  print: (text) => {
    console.log('[MAME]:', text);
  },
  printErr: (text) => {
    console.warn('[MAME Err]:', text);
  },
  setStatus: setStatus,
  locateFile: (path, prefix) => {
    // Help locate the .wasm file if needed
    if (path.endsWith('.wasm')) {
      return '/gng_web.wasm';
    }
    return prefix + path;
  }
};

// Initialize the module
setStatus('Downloading Engine...');
GNGModule(config).then((instance) => {
  console.log('MAME instance initialized');
  setStatus('Running...');

  // Handle canvas focus
  canvas.focus();
  canvas.addEventListener('click', () => {
    canvas.focus();
  });
}).catch((err) => {
  console.error('Failed to initialize MAME:', err);
  setStatus('Error: ' + err);
});
